version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "nodejs",
    "cypress",
    "jest"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "google-java-format"
