version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"

test_patterns = ["*/test/**"]

exclude_patterns = [
    "public/**,",
    "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]
  module_system = "es-modules"
  environment = [
    "jquery",
    "mongo"
  ]
  dialect = "flow"
  skip_doc_coverage = ["class-expression", "method-definition"]  
