-- INSERT INTO public.mandant (id, name, email) VALUES (1, 'USA', 'ab@mail.com');
-- INSERT INTO public.mandant (id, name, email) VALUES (2, 'France', 'ab@mail.com');
-- INSERT INTO public.mandant (id, name, email) VALUES (3, 'Brazil', 'ab@mail.com');
-- INSERT INTO public.mandant (id, name, email) VALUES (4, 'Italy', 'ab@mail.com');
-- INSERT INTO public.mandant (id, name, email) VALUES (5, 'Canada', 'ab@mail.com');
UPDATE mandant SET name = 'USA' WHERE id = 1;
UPDATE mandant SET name = 'France' WHERE id = 2;
UPDATE mandant SET name = 'Brazil' WHERE id = 3;
UPDATE mandant SET name = 'Italy' WHERE id = 4;
UPDATE mandant SET name = 'Canada' WHERE id = 5;