version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "nodejs",
    "cypress",
    "jest",
    "jasmine"
  ]

[[transformers]]
name = "prettier"
