name: DeepSource And Codecov Test Coverage

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: thoser666/TheNurseJavaAngular
      - uses: actions/checkout@v4
      - name: Report results to DeepSource
        run: curl https://deepsource.io/cli | sh
        run: ./bin/deepsource report --analyzer test-coverage --key python --value-file target/surefire-reports

        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}


